pbat2_vars: 
  batch1: 'W'
  batch2: 'X'
  batch3: 'Y'
  batch4: 'Z'

illumina_vars:
  batch1: 'Q'
  batch2: 'R'
  batch3: 'S'
  batch4: 'T'

empty: ['5C', '6C', '5D', '6D', '13G', '14G', '13H', '14H', '23O', '24O', '23P', '24P']

plate: |
  row,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
  A,1A_W_Q,1A_X_R,2A_W_Q,2A_X_R,3A_W_Q,3A_X_R,4A_W_Q,4A_X_R,5A_W_Q,5A_X_R,6A_W_Q,6A_X_R,7A_W_Q,7A_X_R,8A_W_Q,8A_X_R,9A_W_Q,9A_X_R,10A_W_Q,10A_X_R,11A_W_Q,11A_X_R,12A_W_Q,12A_X_R
  B,1A_Y_S,1A_Z_T,2A_Y_S,2A_Z_T,3A_Y_S,3A_Z_T,4A_Y_S,4A_Z_T,5A_Y_S,5A_Z_T,6A_Y_S,6A_Z_T,7A_Y_S,7A_Z_T,8A_Y_S,8A_Z_T,9A_Y_S,9A_Z_T,10A_Y_S,10A_Z_T,11A_Y_S,11A_Z_T,12A_Y_S,12A_Z_T
  C,1B_W_Q,1B_X_R,2B_W_Q,2B_X_R,3B_W_Q,3B_X_R,4B_W_Q,4B_X_R,5B_W_Q,5B_X_R,6B_W_Q,6B_X_R,7B_W_Q,7B_X_R,8B_W_Q,8B_X_R,9B_W_Q,9B_X_R,10B_W_Q,10B_X_R,11B_W_Q,11B_X_R,12B_W_Q,12B_X_R
  D,1B_Y_S,1B_Z_T,2B_Y_S,2B_Z_T,3B_Y_S,3B_Z_T,4B_Y_S,4B_Z_T,5B_Y_S,5B_Z_T,6B_Y_S,6B_Z_T,7B_Y_S,7B_Z_T,8B_Y_S,8B_Z_T,9B_Y_S,9B_Z_T,10B_Y_S,10B_Z_T,11B_Y_S,11B_Z_T,12B_Y_S,12B_Z_T
  E,1C_W_Q,1C_X_R,2C_W_Q,2C_X_R,3C_W_Q,3C_X_R,4C_W_Q,4C_X_R,5C_W_Q,5C_X_R,6C_W_Q,6C_X_R,7C_W_Q,7C_X_R,8C_W_Q,8C_X_R,9C_W_Q,9C_X_R,10C_W_Q,10C_X_R,11C_W_Q,11C_X_R,12C_W_Q,12C_X_R
  F,1C_Y_S,1C_Z_T,2C_Y_S,2C_Z_T,3C_Y_S,3C_Z_T,4C_Y_S,4C_Z_T,5C_Y_S,5C_Z_T,6C_Y_S,6C_Z_T,7C_Y_S,7C_Z_T,8C_Y_S,8C_Z_T,9C_Y_S,9C_Z_T,10C_Y_S,10C_Z_T,11C_Y_S,11C_Z_T,12C_Y_S,12C_Z_T
  G,1D_W_Q,1D_X_R,2D_W_Q,2D_X_R,3D_W_Q,3D_X_R,4D_W_Q,4D_X_R,5D_W_Q,5D_X_R,6D_W_Q,6D_X_R,7D_W_Q,7D_X_R,8D_W_Q,8D_X_R,9D_W_Q,9D_X_R,10D_W_Q,10D_X_R,11D_W_Q,11D_X_R,12D_W_Q,12D_X_R
  H,1D_Y_S,1D_Z_T,2D_Y_S,2D_Z_T,3D_Y_S,3D_Z_T,4D_Y_S,4D_Z_T,5D_Y_S,5D_Z_T,6D_Y_S,6D_Z_T,7D_Y_S,7D_Z_T,8D_Y_S,8D_Z_T,9D_Y_S,9D_Z_T,10D_Y_S,10D_Z_T,11D_Y_S,11D_Z_T,12D_Y_S,12D_Z_T
  I,1E_W_Q,1E_X_R,2E_W_Q,2E_X_R,3E_W_Q,3E_X_R,4E_W_Q,4E_X_R,5E_W_Q,5E_X_R,6E_W_Q,6E_X_R,7E_W_Q,7E_X_R,8E_W_Q,8E_X_R,9E_W_Q,9E_X_R,10E_W_Q,10E_X_R,11E_W_Q,11E_X_R,12E_W_Q,12E_X_R
  J,1E_Y_S,1E_Z_T,2E_Y_S,2E_Z_T,3E_Y_S,3E_Z_T,4E_Y_S,4E_Z_T,5E_Y_S,5E_Z_T,6E_Y_S,6E_Z_T,7E_Y_S,7E_Z_T,8E_Y_S,8E_Z_T,9E_Y_S,9E_Z_T,10E_Y_S,10E_Z_T,11E_Y_S,11E_Z_T,12E_Y_S,12E_Z_T
  K,1F_W_Q,1F_X_R,2F_W_Q,2F_X_R,3F_W_Q,3F_X_R,4F_W_Q,4F_X_R,5F_W_Q,5F_X_R,6F_W_Q,6F_X_R,7F_W_Q,7F_X_R,8F_W_Q,8F_X_R,9F_W_Q,9F_X_R,10F_W_Q,10F_X_R,11F_W_Q,11F_X_R,12F_W_Q,12F_X_R
  L,1F_Y_S,1F_Z_T,2F_Y_S,2F_Z_T,3F_Y_S,3F_Z_T,4F_Y_S,4F_Z_T,5F_Y_S,5F_Z_T,6F_Y_S,6F_Z_T,7F_Y_S,7F_Z_T,8F_Y_S,8F_Z_T,9F_Y_S,9F_Z_T,10F_Y_S,10F_Z_T,11F_Y_S,11F_Z_T,12F_Y_S,12F_Z_T
  M,1G_W_Q,1G_X_R,2G_W_Q,2G_X_R,3G_W_Q,3G_X_R,4G_W_Q,4G_X_R,5G_W_Q,5G_X_R,6G_W_Q,6G_X_R,7G_W_Q,7G_X_R,8G_W_Q,8G_X_R,9G_W_Q,9G_X_R,10G_W_Q,10G_X_R,11G_W_Q,11G_X_R,12G_W_Q,12G_X_R
  N,1G_Y_S,1G_Z_T,2G_Y_S,2G_Z_T,3G_Y_S,3G_Z_T,4G_Y_S,4G_Z_T,5G_Y_S,5G_Z_T,6G_Y_S,6G_Z_T,7G_Y_S,7G_Z_T,8G_Y_S,8G_Z_T,9G_Y_S,9G_Z_T,10G_Y_S,10G_Z_T,11G_Y_S,11G_Z_T,12G_Y_S,12G_Z_T
  O,1H_W_Q,1H_X_R,2H_W_Q,2H_X_R,3H_W_Q,3H_X_R,4H_W_Q,4H_X_R,5H_W_Q,5H_X_R,6H_W_Q,6H_X_R,7H_W_Q,7H_X_R,8H_W_Q,8H_X_R,9H_W_Q,9H_X_R,10H_W_Q,10H_X_R,11H_W_Q,11H_X_R,12H_W_Q,12H_X_R
  P,1H_Y_S,1H_Z_T,2H_Y_S,2H_Z_T,3H_Y_S,3H_Z_T,4H_Y_S,4H_Z_T,5H_Y_S,5H_Z_T,6H_Y_S,6H_Z_T,7H_Y_S,7H_Z_T,8H_Y_S,8H_Z_T,9H_Y_S,9H_Z_T,10H_Y_S,10H_Z_T,11H_Y_S,11H_Z_T,12H_Y_S,12H_Z_T



