experiment: my_experiment
plate_id: my_plate_id
description: blah blah

fastq_dir: path_to_fastq_dir
workdir: path_to_workdir

exp_indexes: 
  batch1: ['13E', 'ZMillu5']
  batch2: ['13F', 'ZMillu6']
  batch3: ['14C', 'ZMillu9']
  batch4: ['14D', 'ZMillu10']

genome: mm9
pipeline_steps:        
  - demultiplexing     
  - mapping
  - bam2smat 

