# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_meth <- function(idxs, db_dir, cells, CPG_NUM) {
    .Call('_sc5mc_mean_meth', PACKAGE = 'sc5mc', idxs, db_dir, cells, CPG_NUM)
}

bin_meth <- function(idxs, bins, db_dir, cells, CPG_NUM) {
    .Call('_sc5mc_bin_meth', PACKAGE = 'sc5mc', idxs, bins, db_dir, cells, CPG_NUM)
}

bin_meth_per_cell_cpp <- function(idxs, bins, db_dir, cells, CPG_NUM) {
    .Call('_sc5mc_bin_meth_per_cell_cpp', PACKAGE = 'sc5mc', idxs, bins, db_dir, cells, CPG_NUM)
}

