# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_meth <- function(cgdb, idxs, cells) {
    .Call('_sc5mc_mean_meth', PACKAGE = 'sc5mc', cgdb, idxs, cells)
}

bin_meth <- function(cgdb, idxs, bins, cells) {
    .Call('_sc5mc_bin_meth', PACKAGE = 'sc5mc', cgdb, idxs, bins, cells)
}

extract_sc_data <- function(cgdb, idxs, cells) {
    .Call('_sc5mc_extract_sc_data', PACKAGE = 'sc5mc', cgdb, idxs, cells)
}

bin_meth_per_cell_cpp <- function(cgdb, idxs, bins, cells) {
    .Call('_sc5mc_bin_meth_per_cell_cpp', PACKAGE = 'sc5mc', cgdb, idxs, bins, cells)
}

freemem <- function(cgdb) {
    invisible(.Call('_sc5mc_freemem', PACKAGE = 'sc5mc', cgdb))
}

